version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    working_dir: /var/www
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/var/www


  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.docker
    working_dir: /var/www
    volumes_from:
        - app
    links:
        - db
    ports:
      - 8080:80


  # The DB Server
  db:
    image: mysql:5.7
    volumes:
        - "./docker/data/db:/var/lib/mysql"
    restart: always
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: V25mX47XhF3ZpeT8
        MYSQL_DATABASE: BookStore
        MYSQL_USER: book
        MYSQL_PASSWORD: book@123
    
  # The phpMyAdmin
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
       - "8088:80"
    links:
       - db
    environment:
        PMA_HOST: db